### ISSUE TITLE
请问获取准考证的那个密钥是怎么取的？

### ISSUE THREAD

**Issue by sostuts** [liujin1995/CET#1]
如题，是反编译那个99宿舍软件吗

**Comment by liujin1995** [comment]
不是反编译，是od调试

**Comment by sostuts** [comment]
![od_1](https://cloud.githubusercontent.com/assets/16024864/23127549/659b3b14-f7b6-11e6-9863-c1b17d2a89c0.jpg)
不太会od... 请问如何快速定位到密钥那里呢？ 被这个打开后就卡住了。

**Comment by liujin1995** [comment]
没有快速定位，只能从找准考证的地方，下断点，一步步去运行，密钥会在寄存器里展示出来

**Comment by sostuts** [comment]
![od_2](https://cloud.githubusercontent.com/assets/16024864/23128367/a54a6264-f7b9-11e6-88f8-4c66e6e99f60.jpg)
下断点运行之后，遇见第一个死循环？是不是判断用户选择哪个按钮（找回准考证 || 保存成绩截图）？

**Comment by liujin1995** [comment]
没有研究过，我只是去找到我要的

**Comment by sostuts** [comment]
弱弱的问句，大牛可以出个教程么…
